services:
  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: sh -c "yarn && yarn dev"
    depends_on:
      - db

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:3000"
    environment:
      - NODE_ENV=development
    command: sh -c "yarn && yarn start"

  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend/db-init-scripts:/docker-entrypoint-initdb.d

volumes:
  pg_data:
