services:
  backend:
    image: ghcr.io/jemeyer/ai-maestro-backend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db

  frontend:
    image: ghcr.io/jemeyer/ai-maestro-frontend:latest
    ports:
      - "80:80"

  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend/db-init-scripts:/docker-entrypoint-initdb.d

volumes:
  pg_data:
